import { useState } from 'react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { PersistentCTA } from '@/components/PersistentCTA';
import { SEO, FAQSchema } from '@/components/SEO';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { Link } from 'wouter';
import { Button } from '@/components/ui/button';
import { ChevronDown, ChevronUp, Shield } from 'lucide-react';

const faqs = [
  {
    question: 'What is cybersecurity?',
    answer: 'Cybersecurity is the practice of protecting computers, networks, programs, and data from unauthorized access, damage, or attack. For businesses, it includes measures like firewalls, encryption, access controls, monitoring, and employee training to prevent data breaches and cyber attacks.',
  },
  {
    question: 'Why is cybersecurity important for Zimbabwean businesses?',
    answer: 'Cyber attacks are increasing across Africa. Zimbabwean businesses are targeted for financial data, customer records, and as part of global attack campaigns. A single breach can cost thousands of dollars in recovery, damage your reputation, and result in legal liability. Proactive cybersecurity is far cheaper than reacting to an attack.',
  },
  {
    question: 'What are the most common cyber threats?',
    answer: 'The most common threats are: phishing emails that trick employees into revealing credentials, ransomware that encrypts your files and demands payment, malware that steals data, insider threats from employees, and weak passwords that allow unauthorized access.',
  },
  {
    question: 'What is multi-factor authentication (MFA)?',
    answer: 'MFA adds a second verification step beyond your password — typically a code sent to your phone or generated by an app. Even if someone steals your password, they cannot access your account without the second factor. We recommend MFA for all business accounts.',
  },
  {
    question: 'How does ClawnCore protect my data?',
    answer: 'We use AES-256 encryption for data at rest, TLS 1.3 for data in transit, role-based access controls, regular automated backups, and continuous monitoring. Our cloud infrastructure is designed with multiple layers of security to protect against both external attacks and internal risks.',
  },
  {
    question: 'What is threat detection?',
    answer: 'Threat detection uses AI and monitoring tools to continuously watch your network, systems, and user activity for suspicious behavior. When a potential threat is identified, it can be automatically contained and your team alerted — often before any damage occurs.',
  },
  {
    question: 'How often should I update my security?',
    answer: 'Security is not a one-time setup. We recommend: continuous monitoring (automated), quarterly security reviews, immediate patching of critical vulnerabilities, annual penetration testing, and regular employee security training. Our managed security services handle this for you.',
  },
  {
    question: 'Do small businesses need cybersecurity?',
    answer: 'Yes. Small businesses are actually more vulnerable because they often lack dedicated security staff. Hackers target small businesses precisely because they are easier to attack. Our Starter plan provides essential protection at an affordable price.',
  },
  {
    question: 'What should I do if I suspect a breach?',
    answer: 'Immediately: disconnect affected systems from the network, change all passwords, and contact your security team. Do not try to investigate or fix it yourself — this can destroy evidence. ClawnCore clients should call our emergency response line for immediate assistance.',
  },
  {
    question: 'How much does cybersecurity cost?',
    answer: 'Costs depend on your organization size and risk level. Our Starter plan for small businesses provides essential protection at an affordable monthly rate. The cost of prevention is always less than the cost of recovery from a breach, which can average $50,000+ for small businesses.',
  },
];

export default function FAQCybersecurity() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-cc-darker text-gray-900 dark:text-white">
      <SEO
        title="Cybersecurity FAQ"
        description="Frequently asked questions about cybersecurity, threat detection, data protection, and security best practices for Zimbabwean businesses."
        keywords={['cybersecurity FAQ Zimbabwe', 'IT security questions Africa', 'data protection FAQ', 'business cybersecurity']}
      />
      <FAQSchema faqs={faqs} />

      <Header />

      <main>
        <section className="relative bg-gradient-to-br from-[#0f172a] to-[#1e293b] py-24 sm:py-32 text-white">
          <div className="container mx-auto px-4 sm:px-6">
            <Breadcrumbs
              items={[
                { name: 'Resources', url: '/resources' },
                { name: 'FAQ', url: '/resources/faq' },
                { name: 'Cybersecurity', url: '/resources/faq/cybersecurity' },
              ]}
              className="text-white/70 mb-8"
            />
            <div className="max-w-4xl">
              <Shield className="h-12 w-12 text-[#38bdf8] mb-6" />
              <h1 className="text-4xl sm:text-5xl md:text-6xl font-black tracking-tight mb-6">
                Cybersecurity <span className="text-[#38bdf8]">FAQ</span>
              </h1>
              <p className="text-xl sm:text-2xl text-white/90 leading-relaxed">
                Everything you need to know about protecting your business from cyber threats in Zimbabwe.
              </p>
            </div>
          </div>
        </section>

        <section className="py-20 sm:py-28">
          <div className="container mx-auto px-4 sm:px-6">
            <div className="max-w-3xl mx-auto">
              <div className="space-y-4">
                {faqs.map((faq, index) => (
                  <div
                    key={index}
                    className="rounded-2xl bg-white dark:bg-cc-card border border-gray-200 dark:border-white/10 overflow-hidden"
                  >
                    <button
                      onClick={() => setOpenIndex(openIndex === index ? null : index)}
                      className="w-full flex items-center justify-between p-6 text-left"
                    >
                      <h3 className="text-lg font-bold pr-4">{faq.question}</h3>
                      {openIndex === index ? (
                        <ChevronUp className="h-5 w-5 text-[#0284c7] flex-shrink-0" />
                      ) : (
                        <ChevronDown className="h-5 w-5 text-gray-400 flex-shrink-0" />
                      )}
                    </button>
                    {openIndex === index && (
                      <div className="px-6 pb-6">
                        <p className="text-gray-600 dark:text-slate-300 leading-relaxed">
                          {faq.answer}
                        </p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section className="py-20 sm:py-28 bg-gradient-to-br from-[#0284c7] to-[#0369a1] text-white">
          <div className="container mx-auto px-4 sm:px-6 text-center">
            <h2 className="text-3xl sm:text-4xl font-black mb-6">Protect Your Business Today</h2>
            <p className="text-xl text-white/90 max-w-2xl mx-auto mb-8">
              Get a free security assessment for your organization.
            </p>
            <Link href="/get-started">
              <Button className="h-12 px-8 bg-white text-[#0284c7] hover:bg-gray-100 font-bold">Get Protected</Button>
            </Link>
          </div>
        </section>
      </main>

      <Footer />
      <PersistentCTA />
    </div>
  );
}
