export type DepartmentId = 'ai' | 'drone' | 'cyber' | 'cloud' | 'analytics';

export interface CareerRole {
  id: string;
  title: string;
  department: DepartmentId;
  departmentName: string;
  location: string;
  type: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
  benefits: string[];
  salary?: string;
  skills: string[];
  postedDate: string;
  image: string;
}

export const DEPARTMENTS: { id: DepartmentId; name: string; description: string; icon: string; color: string; image: string; heroImage: string }[] = [
  { id: 'ai', name: 'ClawnAI Core', description: 'Building adaptive neural systems and autonomous AI platforms that learn, evolve, and solve real-world problems across agriculture, security, and enterprise.', icon: 'activity', color: '#3b82f6', image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=600&q=80', heroImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1400&q=85' },
  { id: 'drone', name: 'Drone Operations', description: 'Engineering autonomous flight systems, swarm intelligence, and precision aerial intelligence for agriculture, surveying, and environmental monitoring.', icon: 'cpu', color: '#0ea5e9', image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=600&q=80', heroImage: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1400&q=85' },
  { id: 'cyber', name: 'Cybersecurity Mesh', description: 'Designing zero-trust architectures, quantum-resistant cryptography, and autonomous threat defense systems for enterprise-grade security.', icon: 'shield', color: '#10b981', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80', heroImage: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1400&q=85' },
  { id: 'cloud', name: 'Cloud Infrastructure', description: 'Building planetary-scale distributed systems, edge computing networks, and high-availability infrastructure powering the entire ClawnCore ecosystem.', icon: 'network', color: '#6366f1', image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80', heroImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1400&q=85' },
  { id: 'analytics', name: 'Global Analytics', description: 'Transforming raw data into actionable intelligence through predictive models, real-time dashboards, and advanced visualization systems.', icon: 'chart', color: '#8b5cf6', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80', heroImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=85' },
];

export const BENEFITS = [
  { title: 'Health & Wellness', description: 'Comprehensive medical, dental, and vision coverage for you and your family.', icon: 'heart' },
  { title: 'Remote-First', description: 'Work from anywhere in the world. We trust our team to deliver results, not hours.', icon: 'globe' },
  { title: 'Learning Budget', description: '$5,000 annual learning stipend for conferences, courses, certifications, and books.', icon: 'book' },
  { title: 'Equity Package', description: 'Meaningful equity stakes so you share in the value you help create.', icon: 'chart' },
  { title: 'Unlimited PTO', description: 'Take the time you need to recharge. We encourage minimum 4 weeks per year.', icon: 'clock' },
  { title: 'Team Events', description: 'Quarterly offsites, annual summit, and team building experiences across the globe.', icon: 'users' },
  { title: 'Parental Leave', description: '16 weeks paid parental leave for all new parents, regardless of gender.', icon: 'heart' },
  { title: 'Sabbatical Program', description: 'After 4 years, take a 6-week paid sabbatical to travel, learn, or rest.', icon: 'clock' },
];

export const CAREER_ROLES: CareerRole[] = [
  // ═══════════════════ AI DEPARTMENT ═══════════════════
  {
    id: 'role-ai-1',
    title: 'Neural Systems Architect',
    department: 'ai',
    departmentName: 'ClawnAI Core',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$150,000 – $200,000',
    postedDate: '2025-08-15',
    description: 'Design and deploy adaptive neural pathways for our next-generation autonomous systems. You will work on unconstrained machine learning models that restructure their own architecture based on telemetry data from drones, sensors, and enterprise platforms.',
    responsibilities: [
      'Architect and implement novel neural network architectures for multi-modal data processing',
      'Design self-evolving model pipelines that adapt to changing data distributions',
      'Lead research initiatives in transfer learning and few-shot adaptation for edge deployment',
      'Collaborate with the drone and agriculture teams to deploy models in field conditions',
      'Mentor junior researchers and establish best practices for reproducible ML research',
    ],
    requirements: [
      '5+ years of experience in machine learning engineering or research',
      'Deep expertise in PyTorch or TensorFlow with production deployment experience',
      'Published research or significant open-source contributions in neural architecture search',
      'Experience with model optimization for edge devices (quantization, pruning, distillation)',
      'Strong programming skills in Python and at least one systems language (Rust, C++, or Go)',
    ],
    benefits: ['Full remote flexibility', 'Conference attendance budget', 'GPU compute allocation', 'Research publication support'],
    skills: ['PyTorch', 'TensorFlow', 'Neural Architecture Search', 'Rust', 'Python'],
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-ai-2',
    title: 'ML Operations Engineer',
    department: 'ai',
    departmentName: 'ClawnAI Core',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$130,000 – $175,000',
    postedDate: '2025-08-20',
    description: 'Build and maintain the infrastructure that takes machine learning models from research notebooks to production systems serving millions of predictions per day across the ClawnCore ecosystem.',
    responsibilities: [
      'Design and manage ML pipelines using Kubeflow, MLflow, or similar orchestration tools',
      'Implement model versioning, A/B testing frameworks, and automated rollback systems',
      'Build monitoring dashboards for model drift, latency, and throughput metrics',
      'Optimize inference serving for real-time and batch prediction workloads',
      'Collaborate with data scientists to streamline the path from experimentation to production',
    ],
    requirements: [
      '3+ years of MLOps or DevOps experience with machine learning systems',
      'Hands-on experience with Kubernetes, Docker, and cloud platforms (AWS/GCP/Azure)',
      'Familiarity with ML frameworks and model serving tools (TensorFlow Serving, Triton, ONNX)',
      'Strong scripting skills in Python and Bash',
      'Experience with CI/CD pipelines and infrastructure-as-code (Terraform, Pulumi)',
    ],
    benefits: ['Full remote flexibility', 'Home office setup budget', 'Annual learning stipend', 'Flexible hours'],
    skills: ['Kubernetes', 'MLOps', 'Python', 'Docker', 'Terraform'],
    image: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-ai-3',
    title: 'Computer Vision Scientist',
    department: 'ai',
    departmentName: 'ClawnAI Core',
    location: 'Hybrid / Lab',
    type: 'Full-Time',
    salary: '$140,000 – $185,000',
    postedDate: '2025-08-10',
    description: 'Develop computer vision systems that analyze drone imagery, satellite data, and industrial video feeds to detect crop stress, infrastructure defects, security threats, and environmental changes in real-time.',
    responsibilities: [
      'Develop object detection, segmentation, and classification models for aerial and satellite imagery',
      'Build real-time video analysis pipelines for drone feed processing',
      'Create anomaly detection systems for agricultural and infrastructure monitoring',
      'Optimize vision models for deployment on edge devices and drone hardware',
      'Collaborate with field teams to validate model accuracy against ground truth data',
    ],
    requirements: [
      'PhD or MS in Computer Science, Electrical Engineering, or related field',
      '3+ years of experience in computer vision research or engineering',
      'Expertise in modern vision architectures (YOLO, ViT, SAM, or similar)',
      'Experience with remote sensing, GIS, or geospatial data is a strong plus',
      'Proficiency in Python, OpenCV, and deep learning frameworks',
    ],
    benefits: ['Lab access with GPU clusters', 'Field work opportunities', 'Research publication support', 'Patent bonus program'],
    skills: ['Computer Vision', 'OpenCV', 'PyTorch', 'Remote Sensing', 'YOLO'],
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-ai-4',
    title: 'NLP Engineer',
    department: 'ai',
    departmentName: 'ClawnAI Core',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$135,000 – $180,000',
    postedDate: '2025-08-22',
    description: 'Build natural language processing systems that power intelligent document analysis, multilingual customer support, and automated reporting across the ClawnCore platform.',
    responsibilities: [
      'Design and fine-tune large language models for domain-specific tasks',
      'Build RAG (Retrieval-Augmented Generation) systems for enterprise knowledge bases',
      'Develop multilingual NLP pipelines supporting African and European languages',
      'Create automated document summarization and extraction systems',
      'Implement safety and alignment measures for production NLP systems',
    ],
    requirements: [
      '3+ years of experience in NLP engineering or applied linguistics',
      'Experience with transformer architectures and modern LLM fine-tuning techniques',
      'Proficiency in Python with Hugging Face, LangChain, or similar frameworks',
      'Understanding of prompt engineering, RAG architectures, and vector databases',
      'Experience deploying NLP models at scale with low-latency requirements',
    ],
    benefits: ['Full remote flexibility', 'GPU compute budget', 'Conference travel', 'Flexible schedule'],
    skills: ['NLP', 'Transformers', 'Python', 'LangChain', 'Vector Databases'],
    image: 'https://images.unsplash.com/photo-1531746790095-e5ec7a9d9c3b?auto=format&fit=crop&w=600&q=80',
  },

  // ═══════════════════ DRONE DEPARTMENT ═══════════════════
  {
    id: 'role-drone-1',
    title: 'Swarm Intelligence Engineer',
    department: 'drone',
    departmentName: 'Drone Operations',
    location: 'Hybrid / Lab',
    type: 'Full-Time',
    salary: '$140,000 – $190,000',
    postedDate: '2025-08-12',
    description: 'Develop flocking algorithms and collision-avoidance systems for micro-drone hives. Your code will directly control physical swarms navigating complex terrains in real-time across agricultural fields and urban environments.',
    responsibilities: [
      'Design and implement multi-agent coordination algorithms for drone swarms',
      'Build real-time collision avoidance and path planning systems',
      'Develop communication protocols for decentralized drone coordination',
      'Test and validate swarm behaviors in simulation before field deployment',
      'Optimize algorithms for low-latency execution on embedded hardware',
    ],
    requirements: [
      'MS or PhD in Robotics, Computer Science, or related engineering field',
      '3+ years of experience in multi-robot systems or swarm robotics',
      'Strong C++ and Python skills with ROS 2 experience',
      'Experience with real-time systems and embedded programming',
      'Understanding of control theory, graph theory, and distributed systems',
    ],
    benefits: ['Lab access with drone fleet', 'Field testing travel', 'Patent bonus program', 'Flexible hybrid schedule'],
    skills: ['C++', 'ROS 2', 'Computer Vision', 'Control Systems', 'Python'],
    image: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-drone-2',
    title: 'Flight Systems Developer',
    department: 'drone',
    departmentName: 'Drone Operations',
    location: 'On-site / Lab',
    type: 'Full-Time',
    salary: '$125,000 – $170,000',
    postedDate: '2025-08-18',
    description: 'Build the firmware and flight control software that powers ClawnCore\'s autonomous drone fleet. You will work directly with hardware to ensure safe, reliable, and intelligent flight operations.',
    responsibilities: [
      'Develop and maintain flight control firmware for custom drone platforms',
      'Implement autonomous navigation, takeoff, landing, and emergency procedures',
      'Integrate sensor suites (LiDAR, IMU, GPS, cameras) into flight systems',
      'Build telemetry and health monitoring systems for fleet management',
      'Conduct flight testing and性能 optimization in field conditions',
    ],
    requirements: [
      '3+ years of experience in drone firmware or flight control development',
      'Strong C/C++ skills with experience in embedded systems (ARM, STM32)',
      'Knowledge of flight dynamics, PID control, and sensor fusion',
      'Experience with PX4, ArduPilot, or custom flight stacks',
      'FAA Part 107 certification or willingness to obtain',
    ],
    benefits: ['Hands-on hardware work', 'Flight testing opportunities', 'Equipment budget', 'Patent bonus'],
    skills: ['C/C++', 'Embedded Systems', 'PX4', 'Sensor Fusion', 'ARM'],
    image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-drone-3',
    title: 'Remote Pilot Operations Lead',
    department: 'drone',
    departmentName: 'Drone Operations',
    location: 'Hybrid / Field',
    type: 'Full-Time',
    salary: '$110,000 – $150,000',
    postedDate: '2025-08-25',
    description: 'Lead our remote pilot team managing autonomous and semi-autonomous drone operations across agricultural, surveying, and environmental monitoring missions in Zimbabwe and beyond.',
    responsibilities: [
      'Manage and coordinate daily drone operations across multiple mission sites',
      'Develop standard operating procedures for autonomous and manual flight modes',
      'Train and certify remote pilots on ClawnCore drone platforms',
      'Liaise with regulatory authorities for flight permissions and compliance',
      'Analyze mission data and optimize flight plans for efficiency and safety',
    ],
    requirements: [
      'FAA Part 107 certification (or international equivalent) required',
      '5+ years of professional drone piloting experience',
      'Experience managing teams of remote pilots',
      'Strong understanding of airspace regulations and safety protocols',
      'Willingness to travel to field sites in Zimbabwe and across Africa',
    ],
    benefits: ['Travel opportunities', 'Field work variety', 'Leadership role', 'Equipment provided'],
    skills: ['Drone Piloting', 'FAA Regulations', 'Team Leadership', 'Mission Planning', 'Safety'],
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-drone-4',
    title: 'Drone Data Analyst',
    department: 'drone',
    departmentName: 'Drone Operations',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$100,000 – $140,000',
    postedDate: '2025-08-28',
    description: 'Process and analyze data collected from drone missions including aerial imagery, LiDAR point clouds, multispectral data, and thermal readings to generate actionable insights for agriculture and infrastructure clients.',
    responsibilities: [
      'Process aerial imagery and generate orthomosaics, NDVI maps, and 3D models',
      'Analyze multispectral and thermal data for crop health assessment',
      'Build automated data pipelines for drone mission data processing',
      'Create client-facing reports and dashboards with mission insights',
      'Develop quality assurance processes for drone-collected data',
    ],
    requirements: [
      '2+ years of experience in geospatial analysis or remote sensing',
      'Proficiency in GIS software (QGIS, ArcGIS) and photogrammetry tools',
      'Experience with Python for data processing and visualization',
      'Knowledge of agricultural remote sensing concepts (NDVI, crop indices)',
      'Strong analytical and communication skills',
    ],
    benefits: ['Full remote flexibility', 'GIS software licenses', 'Learning budget', 'Flexible hours'],
    skills: ['GIS', 'Python', 'Remote Sensing', 'QGIS', 'Data Analysis'],
    image: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=600&q=80',
  },

  // ═══════════════════ CYBERSECURITY DEPARTMENT ═══════════════════
  {
    id: 'role-cyber-1',
    title: 'Quantum Defense Strategist',
    department: 'cyber',
    departmentName: 'Cybersecurity Mesh',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$145,000 – $195,000',
    postedDate: '2025-08-14',
    description: 'Engineer post-quantum cryptographic defenses and build zero-trust architectures capable of withstanding advanced persistent threats and next-generation algorithmic attacks across the ClawnCore infrastructure.',
    responsibilities: [
      'Design and implement post-quantum cryptographic protocols for data-at-rest and data-in-transit',
      'Build zero-trust network architectures with micro-segmentation and continuous verification',
      'Lead threat modeling exercises for critical infrastructure and AI systems',
      'Develop automated vulnerability assessment and remediation pipelines',
      'Advise product teams on security architecture and secure coding practices',
    ],
    requirements: [
      '5+ years of experience in cybersecurity engineering or architecture',
      'Deep understanding of cryptographic protocols and post-quantum algorithms (CRYSTALS, NTRU)',
      'Experience with zero-trust architecture implementation (BeyondCorp, SDP)',
      'Strong programming skills in Go, Rust, or Python',
      'Relevant certifications (CISSP, CEH, OSCP) preferred',
    ],
    benefits: ['Full remote flexibility', 'Security conference budget', 'Certification reimbursement', 'Research time allocation'],
    skills: ['Cryptography', 'Go', 'Zero-Trust', 'Network Security', 'Rust'],
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-cyber-2',
    title: 'Security Operations Analyst',
    department: 'cyber',
    departmentName: 'Cybersecurity Mesh',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$110,000 – $155,000',
    postedDate: '2025-08-21',
    description: 'Monitor, detect, and respond to security incidents across the ClawnCore ecosystem. You will be the first line of defense, operating our SOC and managing our security information and event management systems.',
    responsibilities: [
      'Monitor security alerts and investigate potential incidents across all systems',
      'Triage and escalate security events based on severity and impact',
      'Develop and maintain detection rules, playbooks, and response procedures',
      'Conduct log analysis and forensic investigations for security incidents',
      'Generate weekly and monthly security posture reports for leadership',
    ],
    requirements: [
      '3+ years of experience in SOC operations or security analysis',
      'Experience with SIEM tools (Splunk, Elastic Security, or Sentinel)',
      'Knowledge of common attack vectors, MITRE ATT&CK framework, and incident response',
      'Strong analytical skills and attention to detail',
      'Security certifications (CompTIA Security+, GIAC) preferred',
    ],
    benefits: ['24/7 shift flexibility', 'Remote work', 'Certification budget', 'Career advancement path'],
    skills: ['SIEM', 'Incident Response', 'Log Analysis', 'MITRE ATT&CK', 'Python'],
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-cyber-3',
    title: 'Penetration Testing Engineer',
    department: 'cyber',
    departmentName: 'Cybersecurity Mesh',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$130,000 – $175,000',
    postedDate: '2025-08-16',
    description: 'Conduct authorized penetration tests against ClawnCore infrastructure, customer deployments, and AI systems to identify vulnerabilities before adversaries can exploit them.',
    responsibilities: [
      'Perform external and internal penetration tests on network infrastructure and web applications',
      'Conduct red team exercises simulating advanced persistent threat scenarios',
      'Test AI/ML systems for adversarial attacks, data poisoning, and model evasion',
      'Write detailed technical reports with reproduction steps and remediation guidance',
      'Develop custom tools and scripts for automated vulnerability discovery',
    ],
    requirements: [
      '4+ years of experience in penetration testing or offensive security',
      'OffSec OSCP, OSCE, or equivalent certification',
      'Experience with common penetration testing tools (Burp Suite, Metasploit, Nmap)',
      'Knowledge of cloud security testing (AWS, GCP, Azure)',
      'Experience testing AI/ML systems is a strong plus',
    ],
    benefits: ['Full remote flexibility', 'Tool budget', 'Conference attendance', 'Bug bounty participation'],
    skills: ['Penetration Testing', 'Burp Suite', 'Metasploit', 'Cloud Security', 'Go'],
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-cyber-4',
    title: 'Compliance & Governance Lead',
    department: 'cyber',
    departmentName: 'Cybersecurity Mesh',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$120,000 – $165,000',
    postedDate: '2025-08-26',
    description: 'Lead ClawnCore\'s compliance programs across international frameworks including ISO 27001, SOC 2, GDPR, and emerging AI governance standards. Ensure our platform meets the highest security and privacy standards.',
    responsibilities: [
      'Manage compliance programs for ISO 27001, SOC 2, GDPR, and other frameworks',
      'Conduct risk assessments and develop mitigation strategies for regulatory requirements',
      'Lead audit preparation and coordinate with external auditors',
      'Develop internal security policies, training programs, and awareness campaigns',
      'Monitor emerging regulations and advise leadership on compliance obligations',
    ],
    requirements: [
      '5+ years of experience in IT compliance, governance, or risk management',
      'Certified Information Systems Auditor (CISA) or similar certification',
      'Experience managing compliance programs for SaaS or cloud platforms',
      'Knowledge of international data protection regulations (GDPR, CCPA)',
      'Strong documentation and communication skills',
    ],
    benefits: ['Full remote flexibility', 'Certification budget', 'Flexible schedule', 'Leadership role'],
    skills: ['ISO 27001', 'SOC 2', 'GDPR', 'Risk Assessment', 'Policy Writing'],
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
  },

  // ═══════════════════ CLOUD DEPARTMENT ═══════════════════
  {
    id: 'role-cloud-1',
    title: 'Distributed Systems Architect',
    department: 'cloud',
    departmentName: 'Cloud Infrastructure',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$160,000 – $210,000',
    postedDate: '2025-08-11',
    description: 'Build the planetary-scale backbone of ClawnCore. You will design edge computing networks that process petabytes of IoT and drone telemetry with near-zero latency across multiple continents.',
    responsibilities: [
      'Architect distributed systems handling millions of events per second',
      'Design multi-region data replication and consistency strategies',
      'Build edge computing pipelines for low-latency IoT and drone data processing',
      'Lead technical design reviews and establish architectural standards',
      'Optimize system performance, reliability, and cost across cloud providers',
    ],
    requirements: [
      '7+ years of experience in distributed systems engineering',
      'Deep expertise in consensus protocols, distributed databases, and event-driven architectures',
      'Experience designing systems at scale (>1M requests/second)',
      'Proficiency in Go, Rust, or Java with strong systems design skills',
      'Experience with Kubernetes, service meshes, and cloud-native patterns',
    ],
    benefits: ['Full remote flexibility', 'Architecture leadership role', 'Conference budget', 'Stock options'],
    skills: ['Kubernetes', 'Golang', 'gRPC', 'Distributed Databases', 'Rust'],
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-cloud-2',
    title: 'DevOps Engineer',
    department: 'cloud',
    departmentName: 'Cloud Infrastructure',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$125,000 – $170,000',
    postedDate: '2025-08-19',
    description: 'Build and maintain the CI/CD pipelines, infrastructure-as-code, and deployment automation that enables ClawnCore engineering teams to ship code reliably and rapidly across all platforms.',
    responsibilities: [
      'Design and maintain CI/CD pipelines for microservices and monorepo deployments',
      'Manage infrastructure-as-code using Terraform, Pulumi, or Crossplane',
      'Build developer tooling and self-service platforms for engineering teams',
      'Implement observability stacks (logging, metrics, tracing) across all services',
      'Automate incident response and disaster recovery procedures',
    ],
    requirements: [
      '3+ years of experience in DevOps, SRE, or platform engineering',
      'Strong experience with Kubernetes, Docker, and container orchestration',
      'Proficiency in infrastructure-as-code (Terraform preferred)',
      'Experience with CI/CD tools (GitHub Actions, GitLab CI, Jenkins)',
      'Scripting skills in Bash, Python, or Go',
    ],
    benefits: ['Full remote flexibility', 'Home office budget', 'Learning stipend', 'On-call compensation'],
    skills: ['Kubernetes', 'Terraform', 'Docker', 'CI/CD', 'AWS'],
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-cloud-3',
    title: 'Site Reliability Engineer',
    department: 'cloud',
    departmentName: 'Cloud Infrastructure',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$135,000 – $180,000',
    postedDate: '2025-08-23',
    description: 'Ensure the reliability, performance, and availability of ClawnCore\'s production systems. You will build tooling, automate operations, and drive reliability improvements across the entire platform.',
    responsibilities: [
      'Define and maintain SLOs, SLIs, and error budgets for critical services',
      'Build automated monitoring, alerting, and incident response systems',
      'Conduct post-incident reviews and drive reliability improvements',
      'Optimize system performance, capacity planning, and cost efficiency',
      'Participate in on-call rotation and lead incident response when needed',
    ],
    requirements: [
      '4+ years of experience in SRE, infrastructure engineering, or systems administration',
      'Strong experience with Linux systems, networking, and troubleshooting',
      'Proficiency in Python, Go, or similar languages for tooling development',
      'Experience with monitoring tools (Prometheus, Grafana, Datadog)',
      'Understanding of distributed systems failure modes and resilience patterns',
    ],
    benefits: ['Full remote flexibility', 'On-call compensation', 'Conference budget', 'Flexible schedule'],
    skills: ['Linux', 'Prometheus', 'Go', 'Kubernetes', 'Distributed Systems'],
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-cloud-4',
    title: 'Cloud Security Engineer',
    department: 'cloud',
    departmentName: 'Cloud Infrastructure',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$140,000 – $185,000',
    postedDate: '2025-08-27',
    description: 'Secure ClawnCore\'s cloud infrastructure across AWS, GCP, and Azure. Implement security controls, automate compliance checks, and ensure our multi-cloud environment meets enterprise security standards.',
    responsibilities: [
      'Implement security controls across multi-cloud environments (AWS, GCP, Azure)',
      'Build automated security scanning and compliance checking pipelines',
      'Design and manage secrets management, identity, and access control systems',
      'Conduct cloud security architecture reviews for new services and features',
      'Respond to cloud security incidents and conduct forensic analysis',
    ],
    requirements: [
      '4+ years of experience in cloud security engineering',
      'Deep expertise in at least one major cloud provider (AWS, GCP, or Azure)',
      'Experience with cloud security tools (CloudTrail, GuardDuty, Security Command Center)',
      'Knowledge of container security, Kubernetes security, and DevSecOps practices',
      'Relevant certifications (AWS Security Specialty, GCP Professional Security Engineer)',
    ],
    benefits: ['Full remote flexibility', 'Multi-cloud exposure', 'Certification budget', 'Security conference attendance'],
    skills: ['AWS', 'GCP', 'Cloud Security', 'Terraform', 'DevSecOps'],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f2?auto=format&fit=crop&w=600&q=80',
  },

  // ═══════════════════ ANALYTICS DEPARTMENT ═══════════════════
  {
    id: 'role-analytics-1',
    title: 'Predictive Ecosystem Analyst',
    department: 'analytics',
    departmentName: 'Global Analytics',
    location: 'Hybrid / Lab',
    type: 'Full-Time',
    salary: '$125,000 – $170,000',
    postedDate: '2025-08-13',
    description: 'Transform raw planetary data into actionable intelligence. Build visualization layers and predictive models for our smart agriculture, environmental monitoring, and enterprise analytics divisions.',
    responsibilities: [
      'Develop predictive models for agriculture yield, weather, and market forecasting',
      'Build interactive dashboards and visualization layers for enterprise clients',
      'Design data pipelines for real-time analytics on IoT and sensor data',
      'Collaborate with domain experts to translate business questions into analytical frameworks',
      'Present findings and recommendations to technical and non-technical stakeholders',
    ],
    requirements: [
      '3+ years of experience in data science, analytics, or business intelligence',
      'Strong proficiency in Python, R, or SQL for data analysis',
      'Experience with visualization tools (Tableau, Power BI, or custom dashboards)',
      'Knowledge of statistical modeling and machine learning techniques',
      'Experience with geospatial data and agricultural analytics is a plus',
    ],
    benefits: ['Hybrid flexibility', 'Visualization tool licenses', 'Conference attendance', 'Research time'],
    skills: ['Python', 'PostGIS', 'Data Visualization', 'Machine Learning', 'SQL'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-analytics-2',
    title: 'Business Intelligence Developer',
    department: 'analytics',
    departmentName: 'Global Analytics',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$110,000 – $155,000',
    postedDate: '2025-08-24',
    description: 'Design and build the data warehouses, ETL pipelines, and reporting systems that give ClawnCore clients real-time visibility into their operations, performance, and growth metrics.',
    responsibilities: [
      'Design and maintain data warehouse schemas and ETL/ELT pipelines',
      'Build automated reporting systems and self-service analytics platforms',
      'Create and optimize SQL queries and stored procedures for large datasets',
      'Develop data quality frameworks and monitoring dashboards',
      'Partner with product teams to define metrics, KPIs, and data models',
    ],
    requirements: [
      '3+ years of experience in business intelligence or data engineering',
      'Expert SQL skills and experience with data warehousing (Snowflake, BigQuery, Redshift)',
      'Experience with ETL tools (dbt, Airflow, or similar)',
      'Proficiency in BI tools (Looker, Metabase, or custom solutions)',
      'Strong analytical and problem-solving skills',
    ],
    benefits: ['Full remote flexibility', 'Tool licenses provided', 'Learning budget', 'Flexible hours'],
    skills: ['SQL', 'dbt', 'Snowflake', 'Python', 'Looker'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-analytics-3',
    title: 'Data Engineering Lead',
    department: 'analytics',
    departmentName: 'Global Analytics',
    location: 'Remote / Global',
    type: 'Full-Time',
    salary: '$145,000 – $190,000',
    postedDate: '2025-08-17',
    description: 'Lead the data engineering team building the pipelines, platforms, and infrastructure that power all analytics and AI systems across ClawnCore. You will architect the flow of data from ingestion to insight.',
    responsibilities: [
      'Lead a team of data engineers building production data pipelines',
      'Architect the data platform supporting analytics, ML, and reporting workloads',
      'Design real-time and batch data ingestion from IoT devices, APIs, and databases',
      'Establish data governance, quality, and cataloging standards',
      'Collaborate with AI and analytics teams to ensure data readiness for modeling',
    ],
    requirements: [
      '5+ years of experience in data engineering with 2+ years in leadership roles',
      'Expertise in distributed data processing (Spark, Flink, or Kafka Streams)',
      'Strong programming skills in Python, Scala, or Java',
      'Experience with data orchestration (Airflow, Dagster, or Prefect)',
      'Track record of building and scaling data platforms at growth-stage companies',
    ],
    benefits: ['Full remote flexibility', 'Leadership role', 'Stock options', 'Conference budget'],
    skills: ['Apache Spark', 'Kafka', 'Python', 'Airflow', 'Data Modeling'],
    image: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'role-analytics-4',
    title: 'Visualization Specialist',
    department: 'analytics',
    departmentName: 'Global Analytics',
    location: 'Remote / Global',
    type: 'Contract',
    salary: '$90,000 – $130,000',
    postedDate: '2025-08-29',
    description: 'Create stunning, interactive data visualizations and dashboards that make complex analytics accessible to decision-makers. You will work across agriculture, enterprise, and environmental monitoring projects.',
    responsibilities: [
      'Design and build interactive data visualizations using D3.js, Plotly, or Deck.gl',
      'Create responsive dashboard layouts optimized for desktop and mobile',
      'Develop custom chart components and visual encoding systems',
      'Collaborate with UX designers to ensure visual consistency and accessibility',
      'Prototype new visualization concepts for complex multi-dimensional data',
    ],
    requirements: [
      '2+ years of experience in data visualization or frontend development',
      'Strong skills in D3.js, SVG, Canvas, or WebGL for data visualization',
      'Experience with React and modern frontend tooling',
      'Eye for design and understanding of visual perception principles',
      'Portfolio demonstrating interactive data visualization projects',
    ],
    benefits: ['Full remote flexibility', 'Creative freedom', 'Portfolio building', 'Flexible contract terms'],
    skills: ['D3.js', 'React', 'SVG', 'TypeScript', 'Data Visualization'],
    image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=600&q=80',
  },
];
